### ISSUE TITLE
请问你们能够爬取回一些什么字段？能得到是否为赞助帖子或者品牌、广告的标签字段吗

### ISSUE THREAD

**Issue by Alanhahaer** [submato/xhscrawl#10]

**Comment by submato** [comment]
你要看看这些信息在哪个接口返回



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月12日(周二) 中午12:05
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [submato/xhscrawl] 请问你们能够爬取回一些什么字段？能得到是否为赞助帖子或者品牌、广告的标签字段吗 (Issue #10)
