### ISSUE TITLE
demo返回 406，已经填入cookie

### ISSUE THREAD

**Issue by xhacker5000** [submato/xhscrawl#12]
POST request failed. Status code: 406
{"code":-1,"success":false}

**Comment by submato** [comment]
是不是换接口了，demo的逆向只适用于评论接口



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月28日(周六) 下午3:09
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [submato/xhscrawl] demo返回 406，已经填入cookie (Issue #12)




 
POST request failed. Status code: 406
 {"code":-1,"success":false}

**Comment by xhacker5000** [comment]
没有换哈，只是想测试一下，另外您有wechat联系方式吗，正在下Qq

**Comment by xhacker5000** [comment]
param = {
        "note_id": "64c8c8bd000000000c036e95",
        "content": "写的太好啦",
        "at_users":  []
    }
    
    ca

**Comment by submato** [comment]
demo暂不支撑中文，付费版本的支持，尝试一下英文



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月28日(周六) 下午3:12
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [submato/xhscrawl] demo返回 406，已经填入cookie (Issue #12)




 
param = {
 "note_id": "64c8c8bd000000000c036e95",
 "content": "写的太好啦",
 "at_users":  []
 }
 ca
