### ISSUE TITLE
带上x-s和x-t请求code -1

### ISSUE THREAD

**Issue by HJNHNG** [submato/xhscrawl#5]
带上x-s和x-t请求code -1😭

**Comment by wang-zhiyang** [comment]
具体问题是什么



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月3日(周四) 晚上6:09
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [wang-zhiyang/xhscrawl] 带上x-s和x-t请求code -1 (Issue #5)




 
带上x-s和x-t请求code -1😭

**Comment by HJNHNG** [comment]
![image](https://github.com/wang-zhiyang/xhscrawl/assets/65892737/8c17f1e2-d7f9-465e-acf6-f27d3cabe417)
完整代码：
# @Time    : 2023/8/3 17:17
# @Description :
import json
import re
import execjs
import requests

cookie = ''


def GetXs( cookie, api, data):
    with open('xhs.js', 'r', encoding='utf-8') as f:
        jstext = f.read()

    ctx = execjs.compile(jstext)

    match = re.search(r'a1=([^;]+)', cookie)
    a1 = ""
    if match:
        a1 = match.group(1)
    else:
        print("关键参数a1获取失败，请检查你的cookie")
        return {}

    result = ctx.call("get_xs", api, data, a1)
    return result


api = "/api/sns/web/v1/comment/post"  # 评论api
data = {"note_id": "64bd0bf5000000000800d6a1", "content": "2", "at_users": []}  # 所需的参数字典
xs = GetXs(cookie, api, data)
print(json.dumps(xs, indent=4))

headers = {
    "authority": "edith.xiaohongshu.com",
    "accept": "application/json, text/plain, */*",
    "accept-language": "zh-CN,zh;q=0.9,zh-TW;q=0.8",
    "content-type": "application/json;charset=UTF-8",
    "origin": "https://www.xiaohongshu.com",
    "referer": "https://www.xiaohongshu.com/",
    "sec-ch-ua": "\"Not.A/Brand\";v=\"8\", \"Chromium\";v=\"114\", \"Google Chrome\";v=\"114\"",
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": "\"Windows\"",
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "same-site",
    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36",
    "x-b3-traceid": "c08687f76c7e5491",
    "x-s": xs['X-s'],
    "x-t": str(xs['X-t']),
    "Cookie": cookie
}
url = 'https://edith.xiaohongshu.com/api/sns/web/v1/comment/post'
resp = requests.post(url, headers=headers, json=data)
print(resp.text)

**Comment by wang-zhiyang** [comment]
加我qq吧



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月3日(周四) 晚上6:17
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [wang-zhiyang/xhscrawl] 带上x-s和x-t请求code -1 (Issue #5)




 

 完整代码：
 
@time    : 2023/8/3 17:17
 
@description :
 
import json
 import re
 import execjs
 import requests
 
cookie = ''
 
def GetXs( cookie, api, data):
 with open('xhs.js', 'r', encoding='utf-8') as f:
 jstext = f.read()
 ctx = execjs.compile(jstext) match = re.search(r'a1=([^;]+)', cookie) a1 = "" if match:     a1 = match.group(1) else:     print("关键参数a1获取失败，请检查你的cookie")     return {} result = ctx.call("get_xs", api, data, a1) return result  
api = "/api/sns/web/v1/comment/post"  # 评论api
 data = {"note_id": "64bd0bf5000000000800d6a1", "content": "2", "at_users": []}  # 所需的参数字典
 xs = GetXs(cookie, api, data)
 print(json.dumps(xs, indent=4))
 
headers = {
 "authority": "edith.xiaohongshu.com",
 "accept": "application/json, text/plain, /",
 "accept-language": "zh-CN,zh;q=0.9,zh-TW;q=0.8",
 "content-type": "application/json;charset=UTF-8",
 "origin": "https://www.xiaohongshu.com",
 "referer": "https://www.xiaohongshu.com/",
 "sec-ch-ua": ""Not.A/Brand";v="8", "Chromium";v="114", "Google Chrome";v="114"",
 "sec-ch-ua-mobile": "?0",
 "sec-ch-ua-platform": ""Windows"",
 "sec-fetch-dest": "empty",
 "sec-fetch-mode": "cors",
 "sec-fetch-site": "same-site",
 "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36",
 "x-b3-traceid": "c08687f76c7e5491",
 "x-s": xs['X-s'],
 "x-t": str(xs['X-t']),
 "Cookie": cookie
 }
 url = 'https://edith.xiaohongshu.com/api/sns/web/v1/comment/post'
 resp = requests.post(url, headers=headers, json=data)
 print(resp.text)
