### ISSUE TITLE
目前测试下来没能解决406问题

### ISSUE THREAD

**Issue by Peiratooo** [submato/xhscrawl#7]
![image](https://github.com/submato/xhscrawl/assets/111495741/24024657-259b-4bb1-9b73-ecc9035b5ed7)
![image](https://github.com/submato/xhscrawl/assets/111495741/44f81018-625b-4e5d-b50d-fa1ad03eb359)

**Comment by submato** [comment]
406 一般都是自己参数构造有问题



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月14日(周一) 凌晨2:52
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [submato/xhscrawl] 目前测试下来没能解决406问题 (Issue #7)

**Comment by submato** [comment]
直接向我购买源码吧
