### ISSUE TITLE
需要提供帮助，有联系方式吗？

### ISSUE THREAD

**Issue by Linsanxian** [submato/xhscrawl#8]

**Comment by submato** [comment]
就联系这个qq号



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月26日(周六) 上午10:44
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [submato/xhscrawl] 需要提供帮助，有联系方式吗？ (Issue #8)

**Comment by Linsanxian** [comment]
已经申请了，通过一下大佬

**Comment by zhushen12580** [comment]
> 就联系这个qq号
> […](#) ……
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年8月26日(周六) 上午10:44 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [submato/xhscrawl] 需要提供帮助，有联系方式吗？ (Issue #8) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;
> ---原始邮件---
> 发件人: ***@***.***>
> 发送时间: 2023年8月26日(周六) 上午10:44
> 食欲：***@***.***>;
> 抄送：***@***.***>;
> 主题: [submato/xhscrawl] 需要提供帮助，有联系方式吗？（问题 #8）
> 
> 
> 
> 
> 
> —
> 直接回复此电子邮件、在 GitHub 上查看或取消订阅。
> 您收到此消息是因为您订阅了该主题。消息 ID：***@***.***>

大佬 联系

**Comment by lyuinc** [comment]
看不明白，这个东西主要是干嘛的？ 最近打算做一下小红书
